// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtqduJMigNCqWRIqjBaTubhSn8w4BONOU',
    appId: '1:659778191979:web:850a2dacbd9ecf29ba272e',
    messagingSenderId: '659778191979',
    projectId: 'apphrd',
    authDomain: 'apphrd.firebaseapp.com',
    databaseURL: 'https://apphrd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apphrd.appspot.com',
    measurementId: 'G-0YLVJ8GDW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6h4ShCbs9Lsu1uN5yWKT7rwDfAbsC-w',
    appId: '1:659778191979:android:ef1ea2de3245bffaba272e',
    messagingSenderId: '659778191979',
    projectId: 'apphrd',
    databaseURL: 'https://apphrd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apphrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDziFSJgWDGR6Apb0-edpfE-hny28m8LZo',
    appId: '1:659778191979:ios:cb636d2ff37e9565ba272e',
    messagingSenderId: '659778191979',
    projectId: 'apphrd',
    databaseURL: 'https://apphrd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apphrd.appspot.com',
    iosClientId: '659778191979-61egjpk5d5mja88njip857e0jq0qo0p9.apps.googleusercontent.com',
    iosBundleId: 'com.hrdapp.apphrd',
  );
}
